In [ ]:
import pandas as pd

In [ ]:
# Load the structured HDFS dataset

df = pd.read_csv("../datasets/HDFS_2k_structured.csv")

print("Dataset Shape:", df.shape)

df.head()

In [ ]:
print("Hello Jajitha!")

In [1]:
print("Hello Jajitha!")

Hello Jajitha!

In [2]:
import pandas as pd

In [3]:
# Load the structured HDFS dataset

df = pd.read_csv("../datasets/HDFS_2k_structured.csv")

print("Dataset Shape:", df.shape)

df.head()

Dataset Shape: (2000, 6)

,Date,Time,Thread_ID,Level,Component,Message
0,81109,203615,148,INFO,dfs.DataNode$PacketResponder:,PacketResponder 1 for block blk_38865049064139...
1,81109,203807,222,INFO,dfs.DataNode$PacketResponder:,PacketResponder 0 for block blk_-6952295868487...
2,81109,204005,35,INFO,dfs.FSNamesystem:,BLOCK* NameSystem.addStoredBlock: blockMap upd...
3,81109,204015,308,INFO,dfs.DataNode$PacketResponder:,PacketResponder 2 for block blk_82291938032499...
4,81109,204106,329,INFO,dfs.DataNode$PacketResponder:,PacketResponder 2 for block blk_-6670958622368...

In [4]:
# Feature 1: Message Length

df["Message_Length"] = df["Message"].str.len()

df[["Message", "Message_Length"]].head()

                                             Message  Message_Length
0  PacketResponder 1 for block blk_38865049064139...              61
1  PacketResponder 0 for block blk_-6952295868487...              64
2  BLOCK* NameSystem.addStoredBlock: blockMap upd...             121
3  PacketResponder 2 for block blk_82291938032499...              63
4  PacketResponder 2 for block blk_-6670958622368...              64

## Observation: Message Length Feature

A new feature called **Message_Length** was created by calculating the number of characters in each log message.

This converts raw textual information into a numerical feature that can be used by machine learning algorithms. Longer or unusually short log messages may indicate abnormal system behaviour, making this feature potentially useful for anomaly detection.

In [5]:
# Feature 2: Block ID Presence

df["Has_Block_ID"] = df["Message"].str.contains("blk_", regex=False).astype(int)

df[["Message", "Has_Block_ID"]].head()

                                             Message  Has_Block_ID
0  PacketResponder 1 for block blk_38865049064139...             1
1  PacketResponder 0 for block blk_-6952295868487...             1
2  BLOCK* NameSystem.addStoredBlock: blockMap upd...             1
3  PacketResponder 2 for block blk_82291938032499...             1
4  PacketResponder 2 for block blk_-6670958622368...             1

## Observation: Block ID Presence Feature

A binary feature named **Has_Block_ID** was created to indicate whether a log message contains a Hadoop block identifier (`blk_`).

Representing this information numerically allows machine learning models to use the presence or absence of block identifiers as an additional feature during anomaly detection.

In [6]:
# Feature 3: PacketResponder Presence

df["Has_PacketResponder"] = df["Message"].str.contains("PacketResponder", case=False).astype(int)

df[["Message", "Has_PacketResponder"]].head()

                                             Message  Has_PacketResponder
0  PacketResponder 1 for block blk_38865049064139...                    1
1  PacketResponder 0 for block blk_-6952295868487...                    1
2  BLOCK* NameSystem.addStoredBlock: blockMap upd...                    0
3  PacketResponder 2 for block blk_82291938032499...                    1
4  PacketResponder 2 for block blk_-6670958622368...                    1

## Observation: PacketResponder Feature

A binary feature named **Has_PacketResponder** was created to identify whether a log message contains the keyword **PacketResponder**.

PacketResponder is a Hadoop DataNode component responsible for responding to data packet operations. Encoding its presence as a binary feature may help machine learning models distinguish between different categories of system events.

In [7]:
# Feature 4: Error Keyword Presence

df["Has_Error"] = df["Message"].str.contains("error", case=False, na=False).astype(int)

df[["Message", "Has_Error"]].head()

                                             Message  Has_Error
0  PacketResponder 1 for block blk_38865049064139...          0
1  PacketResponder 0 for block blk_-6952295868487...          0
2  BLOCK* NameSystem.addStoredBlock: blockMap upd...          0
3  PacketResponder 2 for block blk_82291938032499...          0
4  PacketResponder 2 for block blk_-6670958622368...          0

## Observation: Error Keyword Feature

A binary feature named **Has_Error** was created to identify whether a log message contains the keyword **error**.

Although the first few HDFS log messages do not contain this keyword, such messages may appear later in the dataset. Including this feature allows anomaly detection models to recognize explicit error-related events.

In [8]:
# Feature 5: Warning Log

df["Is_WARN"] = (df["Level"] == "WARN").astype(int)

df[["Level", "Is_WARN"]].head()

  Level  Is_WARN
0  INFO        0
1  INFO        0
2  INFO        0
3  INFO        0
4  INFO        0

## Observation: Warning Log Feature

A binary feature named **Is_WARN** was created based on the log level.

The feature assigns a value of **1** to warning messages and **0** to informational messages. Since warning events may indicate abnormal system behaviour, this feature is expected to contribute to anomaly detection performance.

In [9]:
# Display all columns

print(df.columns)

df.head()

Index(['Date', 'Time', 'Thread_ID', 'Level', 'Component', 'Message',
       'Message_Length', 'Has_Block_ID', 'Has_PacketResponder', 'Has_Error',
       'Is_WARN'],
      dtype='str')

,Date,Time,Thread_ID,Level,Component,Message,Message_Length,Has_Block_ID,Has_PacketResponder,Has_Error,Is_WARN
0,81109,203615,148,INFO,dfs.DataNode$PacketResponder:,PacketResponder 1 for block blk_38865049064139...,61,1,1,0,0
1,81109,203807,222,INFO,dfs.DataNode$PacketResponder:,PacketResponder 0 for block blk_-6952295868487...,64,1,1,0,0
2,81109,204005,35,INFO,dfs.FSNamesystem:,BLOCK* NameSystem.addStoredBlock: blockMap upd...,121,1,0,0,0
3,81109,204015,308,INFO,dfs.DataNode$PacketResponder:,PacketResponder 2 for block blk_82291938032499...,63,1,1,0,0
4,81109,204106,329,INFO,dfs.DataNode$PacketResponder:,PacketResponder 2 for block blk_-6670958622368...,64,1,1,0,0

In [10]:
# Check dataset shape after feature engineering

print("Dataset Shape:", df.shape)

Dataset Shape: (2000, 11)

# Feature Engineering Summary

Five new features were successfully engineered from the structured HDFS log dataset.

The engineered features include:

- Message_Length
- Has_Block_ID
- Has_PacketResponder
- Has_Error
- Is_WARN

These features transform raw log messages into numerical and binary representations that can be used as inputs for anomaly detection algorithms in subsequent experiments.